name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Java 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. Gradle Wrapper에 실행 권한을 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x backend/gradlew

      # 3. application.properties, AuthKey 생성
      - name: create resources folder if not exists
        run: mkdir -p backend/src/main/resources

      - name: set up application.properties
        run: echo "${{ secrets.APPLICATION }}" > backend/src/main/resources/application.yaml

      # 4. 백엔드 Gradle 빌드
      - name: Build with Gradle (Backend)
        run: |
          cd backend
          ./gradlew clean bootJar
